[package]
name = "field_path"
description = "Type-safe, no-std field access and reflection utilities."
version = "0.5.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nixonyh/field_path"
readme = "README.md"
exclude = ["/assets/", "/.github/", "/examples/"]
keywords = ["macro", "field", "path", "lens"]
categories = ["no-std", "rust-patterns"]
