[workspace]
resolver = "2"
members = ["crates/*", ]

[workspace.package]
version = "0.3.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/voxell-tech/field_path"

[workspace.dependencies]
field_path = { version = "0.3.0", path = "crates/field_path" }
field_path_derive = { version = "0.3.0", path = "crates/field_path_derive" }
hashbrown = { version = "0.16.1", default-features = false, features = ["default-hasher", "inline-more"] }
linkme = "0.3.35"
macro_magic = "0.6.0"
